# This is a basic workflow to help you get started with Actions
name: CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy_lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy fin-test
        run: |
          cd fin-test
          python -m pip3 install --upgrade pip
          pip3 install --target ./package yfinance
          cd package
          rm -r pandas numpy *.dist-info
          zip -r9 ${OLDPWD}/lambda_function.zip .
          cd $OLDCWD
          zip -g lambda_function.zip lambda_function.py
          aws s3api put-object --bucket a-api --key lambda_function.zip --body lambda_function.zip
          aws lambda update-function-code --function-name fin-test --s3-bucket a-api --s3-key lambda_function.zip
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          function_name: fin-test
          zip_file: lambda_function.zip
